### ISSUE TITLE
ModuleResult instantiation fails if grade is nil

### ISSUE THREAD

**Issue by danielkza** [mezuro/kalibro_client_py#44]
We haven't accounted for this case, it happened while we were testing Prezento and had metric results with "missing ranges".

**Comment by rafamanzo** [comment]
Just changed the title because it mislead me into believing that we were actually trying to save those ModuleResults on KalibroProcessor which is not even possible :)

Nevertheless I think we should place a default value for `grade` as `None`. I'll work on a patch and open a PR. Thanks and good catch.
